version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"

  userprofile-db:
    image: postgres:15
    environment:
      POSTGRES_USER: userprofile_user
      POSTGRES_PASSWORD: userprofile_pass
      POSTGRES_DB: userprofile_db
    ports:
      - "5434:5432"

  post-db:
    image: postgres:15
    environment:
      POSTGRES_USER: post_user
      POSTGRES_PASSWORD: post_pass
      POSTGRES_DB: post_db
    ports:
      - "5435:5432"

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
      - auth-db

  userprofile-service:
    build: ./userprofile-service
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq
      - userprofile-db

  post-service:
    build: ./post-service
    ports:
      - "8083:8080"
    depends_on:
      - rabbitmq
      - post-db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - userprofile-service
      - post-service
